# Generated by Django 4.2.2 on 2023-07-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_image_field_image_upload_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='upload',
            new_name='picture',
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(verbose_name='Координаты - Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.FloatField(verbose_name='Координаты - Долгота'),
        ),
    ]
