# Generated by Django 4.2.2 on 2023-06-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_options_remove_image_name_image_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.SmallIntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
